packages:
  - fixtures/*

catalogs:
  dev:
    '@antfu/ni': 25.0.0
    '@eslint/config-inspector': 1.0.2
    '@stylistic/eslint-plugin-migrate': 4.2.0
    '@types/fs-extra': 11.0.4
    '@types/node': 22.14.1
    '@types/prompts': 2.4.9
    '@types/yargs': 17.0.33
    bumpp: 10.2.0
    eslint-plugin-simple-import-sort: 12.1.1
    eslint-typegen: 2.1.0
    esno: 4.8.0
    execa: 9.5.2
    fast-glob: 3.3.3
    fs-extra: 11.3.0
    jiti: 2.4.2
    lint-staged: 15.5.2
    pnpm-workspace-yaml: 0.3.1
    rimraf: 6.0.1
    simple-git-hooks: 2.12.1
    tsup: 8.4.0
    typescript: 5.8.3
  peer:
    '@eslint-react/eslint-plugin': 1.48.4
    eslint-plugin-jest: 28.11.0
    eslint-plugin-react-roblox-hooks: 5.1.0-rbx.1
    eslint: 9.32.0
  prod:
    '@antfu/install-pkg': 1.0.0
    '@clack/prompts': 0.10.1
    '@cspell/eslint-plugin': 8.19.4
    '@eslint-community/eslint-plugin-eslint-comments': 4.5.0
    '@eslint/compat': 1.2.8
    '@eslint/markdown': 7.1.0
    '@isentinel/dict-rbxts': 1.0.1
    '@isentinel/dict-roblox': 1.0.3
    '@shopify/eslint-plugin': 48.0.2
    '@stylistic/eslint-plugin': 6.0.0-beta.1
    '@typescript-eslint/eslint-plugin': 8.34.1
    '@typescript-eslint/parser': 8.34.1
    ansis: 3.17.0
    eslint-config-flat-gitignore: 2.1.0
    eslint-config-prettier: 10.1.5
    eslint-flat-config-utils: 2.0.1
    eslint-merge-processors: 2.0.0
    eslint-plugin-antfu: 3.1.1
    eslint-plugin-arrow-return-style: 1.3.1
    eslint-plugin-better-max-params: 0.0.1
    eslint-plugin-comment-length: 2.2.1
    eslint-plugin-de-morgan: 1.2.1
    eslint-plugin-format-lua: 1.0.1-beta.2
    eslint-plugin-format: 1.0.1
    eslint-plugin-import-x: 4.10.6
    eslint-plugin-jsdoc: 50.6.9
    eslint-plugin-jsonc: 2.20.0
    eslint-plugin-no-only-tests: 3.3.0
    eslint-plugin-package-json: 0.30.0
    eslint-plugin-perfectionist: 4.15.0
    eslint-plugin-pnpm: 0.3.1
    eslint-plugin-promise: 7.2.1
    eslint-plugin-roblox-ts-x: 1.0.1
    eslint-plugin-sentinel: 0.1.1
    eslint-plugin-sonarjs: 3.0.2
    eslint-plugin-toml: 0.12.0
    eslint-plugin-unicorn: 58.0.0
    eslint-plugin-yml: 1.17.0
    jsonc-eslint-parser: 2.4.0
    local-pkg: 1.1.1
    parse-gitignore: 2.0.0
    prettier-plugin-jsdoc: 1.3.2
    prettier: 3.5.3
    prompts: 2.4.2
    toml-eslint-parser: 0.10.0
    yaml-eslint-parser: 1.3.0
    yargs: 17.7.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
